config/routes.rb
GithubGamification::Application.routes.draw do
  get "hooks/index"
  post "hooks/track"
  resources :commit_files

  resources :commits

  resources :repos

  resources :github_accounts

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get "home/index"

  mount Resque::Server, :at => "/resque"

  root 'home#index'

  

end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :repo
  belongs_to :github_account
  has_many :commit_files, :dependent => :destroy
  has_many :commit_points, :dependent => :destroy
  has_many :languages, :through => :commit_points

  validates :sha, :uniqueness => true
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :set_commit, only: [:show, :edit, :update, :destroy]

  # GET /commits
  # GET /commits.json
  def index
    @commits = Commit.all
  end

  # GET /commits/1
  # GET /commits/1.json
  def show
  end

  # GET /commits/new
  def new
    @commit = Commit.new
  end

  # GET /commits/1/edit
  def edit
  end

  # POST /commits
  # POST /commits.json
  def create
    @commit = Commit.new(commit_params)

    respond_to do |format|
      if @commit.save
        format.html { redirect_to @commit, notice: 'Commit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @commit }
      else
        format.html { render action: 'new' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commits/1
  # PATCH/PUT /commits/1.json
  def update
    respond_to do |format|
      if @commit.update(commit_params)
        format.html { redirect_to @commit, notice: 'Commit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.json
  def destroy
    @commit.destroy
    respond_to do |format|
      format.html { redirect_to commits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commit
      @commit = Commit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commit_params
      params.require(:commit).permit(:sha, :url, :message, :repo_id)
    end
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_form.html.erb
<%= form_for(@commit) do |f| %>
  <% if @commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit.errors.count, "error") %> prohibited this commit from being saved:</h2>

      <ul>
      <% @commit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sha %><br>
    <%= f.text_field :sha %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :repo_id %><br>
    <%= f.number_field :repo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commits/edit.html.erb
<h1>Editing commit</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit %> |
<%= link_to 'Back', commits_path %>

app/views/commits/index.html.erb
<h1>Listing commits</h1>

<table>
  <thead>
    <tr>
      <th>Sha</th>
      <th>Url</th>
      <th>Message</th>
      <th>Repo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commits.each do |commit| %>
      <tr>
        <td><%= commit.sha %></td>
        <td><%= commit.url %></td>
        <td><%= commit.message %></td>
        <td><%= commit.repo_id %></td>
        <td><%= link_to 'Show', commit %></td>
        <td><%= link_to 'Edit', edit_commit_path(commit) %></td>
        <td><%= link_to 'Destroy', commit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commit', new_commit_path %>

app/views/commits/new.html.erb
<h1>New commit</h1>

<%= render 'form' %>

<%= link_to 'Back', commits_path %>

app/views/commits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sha:</strong>
  <%= @commit.sha %>
</p>

<p>
  <strong>Url:</strong>
  <%= @commit.url %>
</p>

<p>
  <strong>Message:</strong>
  <%= @commit.message %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @commit.repo_id %>
</p>

<%= link_to 'Edit', edit_commit_path(@commit) %> |
<%= link_to 'Back', commits_path %>