config/routes.rb
GithubGamification::Application.routes.draw do
  get "hooks/index"
  post "hooks/track"
  resources :commit_files

  resources :commits

  resources :repos

  resources :github_accounts

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get "home/index"

  mount Resque::Server, :at => "/resque"

  root 'home#index'

  

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  belongs_to :github_account
  has_many :commits, :dependent => :destroy
  has_many :commit_files, :through => :commits
  has_many :commit_points, :through => :commits

  validates :repo_id, uniqueness: true
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = current_user.repos
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repo }
      else
        format.html { render action: 'new' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:name, :full_name, :description, :owner, :github_account_id)
    end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :github_account_id %><br>
    <%= f.number_field :github_account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Full name</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Github account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.name %></td>
        <td><%= repo.full_name %></td>
        <td><%= repo.description %></td>
        <td><%= repo.owner %></td>
        <td><%= repo.github_account_id %></td>
        <td><%= link_to 'Show', repo %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @repo.full_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repo.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @repo.owner %>
</p>

<p>
  <strong>Github account:</strong>
  <%= @repo.github_account_id %>
</p>

<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>