config/routes.rb
GithubGamification::Application.routes.draw do
  get "hooks/index"
  post "hooks/track"
  resources :commit_files

  resources :commits

  resources :repos

  resources :github_accounts

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get "home/index"

  mount Resque::Server, :at => "/resque"

  root 'home#index'

  

end

app/models/github_account.rb
class GithubAccount < ActiveRecord::Base
  belongs_to :user
  has_many :repos
  has_many :commits
  has_many :commit_files, :through => :commits
  has_many :commit_points, :through => :commits


  def language_point(language_name)
    self.commit_points.joins(:language).where("languages.name = ?", language_name).sum(:point)
  end

end

app/controllers/github_accounts_controller.rb
class GithubAccountsController < ApplicationController
  before_action :set_github_account, only: [:show, :edit, :update, :destroy]

  # GET /github_accounts
  # GET /github_accounts.json
  def index
    @github_accounts = GithubAccount.all
  end

  # GET /github_accounts/1
  # GET /github_accounts/1.json
  def show
  end

  # GET /github_accounts/new
  def new
    @github_account = GithubAccount.new
  end

  # GET /github_accounts/1/edit
  def edit
  end

  # POST /github_accounts
  # POST /github_accounts.json
  def create
    @github_account = GithubAccount.new(github_account_params)

    respond_to do |format|
      if @github_account.save
        format.html { redirect_to @github_account, notice: 'Github account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @github_account }
      else
        format.html { render action: 'new' }
        format.json { render json: @github_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_accounts/1
  # PATCH/PUT /github_accounts/1.json
  def update
    respond_to do |format|
      if @github_account.update(github_account_params)
        format.html { redirect_to @github_account, notice: 'Github account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @github_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_accounts/1
  # DELETE /github_accounts/1.json
  def destroy
    @github_account.destroy
    respond_to do |format|
      format.html { redirect_to github_accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_account
      @github_account = GithubAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def github_account_params
      params.require(:github_account).permit(:login, :token, :user_id)
    end
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/views/github_accounts/_form.html.erb
<%= form_for(@github_account) do |f| %>
  <% if @github_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@github_account.errors.count, "error") %> prohibited this github_account from being saved:</h2>

      <ul>
      <% @github_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/github_accounts/edit.html.erb
<h1>Editing github_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @github_account %> |
<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/index.html.erb
<h1>Listing github_accounts</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Token</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @github_accounts.each do |github_account| %>
      <tr>
        <td><%= github_account.login %></td>
        <td><%= github_account.token %></td>
        <td><%= github_account.user_id %></td>
        <td><%= link_to 'Show', github_account %></td>
        <td><%= link_to 'Edit', edit_github_account_path(github_account) %></td>
        <td><%= link_to 'Destroy', github_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github account', new_github_account_path %>

app/views/github_accounts/new.html.erb
<h1>New github_account</h1>

<%= render 'form' %>

<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @github_account.login %>
</p>

<p>
  <strong>Token:</strong>
  <%= @github_account.token %>
</p>

<p>
  <strong>User:</strong>
  <%= @github_account.user_id %>
</p>

<%= link_to 'Edit', edit_github_account_path(@github_account) %> |
<%= link_to 'Back', github_accounts_path %>