config/routes.rb
GithubGamification::Application.routes.draw do
  get "hooks/index"
  post "hooks/track"
  resources :commit_files

  resources :commits

  resources :repos

  resources :github_accounts

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get "home/index"

  mount Resque::Server, :at => "/resque"

  root 'home#index'

  

end

app/models/commit_file.rb
class CommitFile < ActiveRecord::Base
  belongs_to :commit

  validates :filename, uniqueness: {scope: "commit_id"}

  after_save :calculate_point


  def calculate_point
    extension = File.extname(self.filename)
    language = Language.where("extensions LIKE ?", "%#{extension}%").first if extension.present?

    if language.present?
      point = language.ratio * self.changed_lines if self.changed_lines.present? && language.ratio.present? #TODO this will be changed
      commit_point = CommitPoint.find_by_commit_id_and_language_id(self.commit_id, language.id)
      if commit_point.present?
        commit_point.point += point
      else
        commit_point = CommitPoint.new
        commit_point.commit = self.commit
        commit_point.language = language
        commit_point.point = point
      end
      commit_point.save
    end

  end
end

app/controllers/commit_files_controller.rb
class CommitFilesController < ApplicationController
  before_action :set_commit_file, only: [:show, :edit, :update, :destroy]

  # GET /commit_files
  # GET /commit_files.json
  def index
    @commit_files = CommitFile.all
  end

  # GET /commit_files/1
  # GET /commit_files/1.json
  def show
  end

  # GET /commit_files/new
  def new
    @commit_file = CommitFile.new
  end

  # GET /commit_files/1/edit
  def edit
  end

  # POST /commit_files
  # POST /commit_files.json
  def create
    @commit_file = CommitFile.new(commit_file_params)

    respond_to do |format|
      if @commit_file.save
        format.html { redirect_to @commit_file, notice: 'Commit file was successfully created.' }
        format.json { render action: 'show', status: :created, location: @commit_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @commit_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commit_files/1
  # PATCH/PUT /commit_files/1.json
  def update
    respond_to do |format|
      if @commit_file.update(commit_file_params)
        format.html { redirect_to @commit_file, notice: 'Commit file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @commit_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commit_files/1
  # DELETE /commit_files/1.json
  def destroy
    @commit_file.destroy
    respond_to do |format|
      format.html { redirect_to commit_files_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commit_file
      @commit_file = CommitFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commit_file_params
      params.require(:commit_file).permit(:filename, :additions, :deletions, :changed_lines, :commit_id)
    end
end

app/helpers/commit_files_helper.rb
module CommitFilesHelper
end

app/views/commit_files/_form.html.erb
<%= form_for(@commit_file) do |f| %>
  <% if @commit_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit_file.errors.count, "error") %> prohibited this commit_file from being saved:</h2>

      <ul>
      <% @commit_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :additions %><br>
    <%= f.number_field :additions %>
  </div>
  <div class="field">
    <%= f.label :deletions %><br>
    <%= f.number_field :deletions %>
  </div>
  <div class="field">
    <%= f.label :changed_lines %><br>
    <%= f.number_field :changed_lines %>
  </div>
  <div class="field">
    <%= f.label :commit_id %><br>
    <%= f.number_field :commit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commit_files/edit.html.erb
<h1>Editing commit_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit_file %> |
<%= link_to 'Back', commit_files_path %>

app/views/commit_files/index.html.erb
<h1>Listing commit_files</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Additions</th>
      <th>Deletions</th>
      <th>Changed lines</th>
      <th>Commit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commit_files.each do |commit_file| %>
      <tr>
        <td><%= commit_file.filename %></td>
        <td><%= commit_file.additions %></td>
        <td><%= commit_file.deletions %></td>
        <td><%= commit_file.changed_lines %></td>
        <td><%= commit_file.commit_id %></td>
        <td><%= link_to 'Show', commit_file %></td>
        <td><%= link_to 'Edit', edit_commit_file_path(commit_file) %></td>
        <td><%= link_to 'Destroy', commit_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commit file', new_commit_file_path %>

app/views/commit_files/new.html.erb
<h1>New commit_file</h1>

<%= render 'form' %>

<%= link_to 'Back', commit_files_path %>

app/views/commit_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @commit_file.filename %>
</p>

<p>
  <strong>Additions:</strong>
  <%= @commit_file.additions %>
</p>

<p>
  <strong>Deletions:</strong>
  <%= @commit_file.deletions %>
</p>

<p>
  <strong>Changed lines:</strong>
  <%= @commit_file.changed_lines %>
</p>

<p>
  <strong>Commit:</strong>
  <%= @commit_file.commit_id %>
</p>

<%= link_to 'Edit', edit_commit_file_path(@commit_file) %> |
<%= link_to 'Back', commit_files_path %>